import type { Listing, TransportJob } from '@/lib/data'
import type {
  AccountStatus,
  CarrierProfile,
  DealEvent,
  Message,
  Notification,
  Order,
  Lease,
  Review,
  Submission,
  ThreadRead,
} from '../types'
import {
  compact,
  isoString,
  nullable,
  type Row,
  type TableSpec,
} from './sql-repository'

export const listingTable: TableSpec<Listing> = {
  table: 'listings',
  columns: [
    'id',
    'name',
    'category',
    'maker',
    'model',
    'year',
    'mileage_km',
    'inspection_expires_on',
    'condition',
    'prefecture',
    'city',
    'image',
    'images',
    'summary',
    'deals',
    'sale_price',
    'lease_per_month',
    'residual_lease',
    'residual_lease_credit_rate',
    'residual_lease_credit_cap',
    'seller_name',
    'seller_kind',
    'seller_rating',
    'seller_reviews',
    'tags',
    'owner_user_id',
    'created_at',
    'updated_at',
    'moderation_status',
    'moderation_note',
    'moderated_at',
    'withdrawn_at',
  ],
  toRow: (listing) => [
    listing.id,
    listing.name,
    listing.category,
    listing.maker,
    listing.model,
    listing.year,
    listing.mileageKm,
    nullable(listing.inspectionExpiresOn),
    listing.condition,
    listing.prefecture,
    listing.city,
    listing.image,
    nullable(listing.images),
    listing.summary,
    listing.deals,
    nullable(listing.salePrice),
    nullable(listing.leasePerMonth),
    nullable(listing.residualLease),
    nullable(listing.residualLeaseCreditRate),
    nullable(listing.residualLeaseCreditCap),
    listing.seller.name,
    listing.seller.kind,
    listing.seller.rating,
    listing.seller.reviews,
    listing.tags,
    nullable(listing.ownerUserId),
    nullable(listing.createdAt),
    nullable(listing.updatedAt),
    nullable(listing.moderationStatus),
    nullable(listing.moderationNote),
    nullable(listing.moderatedAt),
    nullable(listing.withdrawnAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      name: row.name as string,
      category: row.category as string,
      maker: row.maker as string,
      model: row.model as string,
      year: row.year as number,
      mileageKm: row.mileage_km as number,
      inspectionExpiresOn:
        (row.inspection_expires_on as string | null) ?? undefined,
      condition: row.condition as Listing['condition'],
      prefecture: row.prefecture as string,
      city: row.city as string,
      image: row.image as string,
      images: (row.images as string[] | null) ?? undefined,
      summary: row.summary as string,
      deals: row.deals as Listing['deals'],
      salePrice: (row.sale_price as number | null) ?? undefined,
      leasePerMonth: (row.lease_per_month as number | null) ?? undefined,
      residualLease: (row.residual_lease as boolean | null) ?? undefined,
      residualLeaseCreditRate:
        (row.residual_lease_credit_rate as number | null) ?? undefined,
      residualLeaseCreditCap:
        (row.residual_lease_credit_cap as number | null) ?? undefined,
      seller: {
        name: row.seller_name as string,
        kind: row.seller_kind as Listing['seller']['kind'],
        rating: row.seller_rating as number,
        reviews: row.seller_reviews as number,
      },
      tags: row.tags as string[],
      ownerUserId: (row.owner_user_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
      moderationStatus:
        (row.moderation_status as Listing['moderationStatus'] | null) ??
        undefined,
      moderationNote: (row.moderation_note as string | null) ?? undefined,
      moderatedAt: isoString(row.moderated_at),
      withdrawnAt: isoString(row.withdrawn_at),
    }),
}

export const transportJobTable: TableSpec<TransportJob> = {
  table: 'transport_jobs',
  columns: [
    'id',
    'vehicle_name',
    'from_location',
    'to_location',
    'distance_km',
    'vehicle_size',
    'vehicle_count',
    'desired_date',
    'reward',
    'status',
    'owner_user_id',
    'created_at',
    'updated_at',
    'moderation_status',
    'moderation_note',
    'moderated_at',
  ],
  toRow: (job) => [
    job.id,
    job.vehicleName,
    job.from,
    job.to,
    job.distanceKm,
    job.vehicleSize,
    job.vehicleCount,
    job.desiredDate,
    job.reward,
    job.status,
    nullable(job.ownerUserId),
    nullable(job.createdAt),
    nullable(job.updatedAt),
    nullable(job.moderationStatus),
    nullable(job.moderationNote),
    nullable(job.moderatedAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      vehicleName: row.vehicle_name as string,
      from: row.from_location as string,
      to: row.to_location as string,
      distanceKm: row.distance_km as number,
      vehicleSize: row.vehicle_size as TransportJob['vehicleSize'],
      vehicleCount: row.vehicle_count as number,
      desiredDate: row.desired_date as string,
      reward: row.reward as number,
      status: row.status as TransportJob['status'],
      ownerUserId: (row.owner_user_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
      moderationStatus:
        (row.moderation_status as TransportJob['moderationStatus'] | null) ??
        undefined,
      moderationNote: (row.moderation_note as string | null) ?? undefined,
      moderatedAt: isoString(row.moderated_at),
    }),
}

export const submissionTable: TableSpec<Submission> = {
  table: 'submissions',
  columns: [
    'id',
    'kind',
    'target_id',
    'user_id',
    'received_at',
    'payload',
    'status',
  ],
  toRow: (submission) => [
    submission.id,
    submission.kind,
    nullable(submission.targetId),
    nullable(submission.userId),
    submission.receivedAt,
    JSON.stringify(submission.payload),
    nullable(submission.status),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      kind: row.kind as Submission['kind'],
      targetId: (row.target_id as string | null) ?? undefined,
      userId: (row.user_id as string | null) ?? undefined,
      receivedAt: isoString(row.received_at) as string,
      payload: row.payload as Record<string, unknown>,
      status: (row.status as Submission['status'] | null) ?? undefined,
    }),
}

export const messageTable: TableSpec<Message> = {
  table: 'messages',
  columns: ['id', 'thread_id', 'sender_user_id', 'body', 'created_at'],
  toRow: (message) => [
    message.id,
    message.threadId,
    message.senderUserId,
    message.body,
    message.createdAt,
  ],
  fromRow: (row: Row) => ({
    id: row.id as string,
    threadId: row.thread_id as string,
    senderUserId: row.sender_user_id as string,
    body: row.body as string,
    createdAt: isoString(row.created_at) as string,
  }),
}

export const leaseTable: TableSpec<Lease> = {
  table: 'leases',
  columns: [
    'id',
    'listing_id',
    'lessee_user_id',
    'start_date',
    'end_date',
    'months',
    'lease_per_month',
    'lease_total',
    'sale_price',
    'credit_rate',
    'credit_cap',
    'status',
    'buyout_price',
    'created_at',
    'updated_at',
  ],
  toRow: (lease) => [
    lease.id,
    lease.listingId,
    lease.lesseeUserId,
    lease.startDate,
    lease.endDate,
    lease.months,
    lease.leasePerMonth,
    lease.leaseTotal,
    nullable(lease.salePrice),
    nullable(lease.creditRate),
    nullable(lease.creditCap),
    lease.status,
    nullable(lease.buyoutPrice),
    lease.createdAt,
    lease.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      lesseeUserId: row.lessee_user_id as string,
      startDate: row.start_date as string,
      endDate: row.end_date as string,
      months: row.months as number,
      leasePerMonth: row.lease_per_month as number,
      leaseTotal: row.lease_total as number,
      salePrice: (row.sale_price as number | null) ?? undefined,
      creditRate: (row.credit_rate as number | null) ?? undefined,
      creditCap: (row.credit_cap as number | null) ?? undefined,
      status: row.status as Lease['status'],
      buyoutPrice: (row.buyout_price as number | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const accountStatusTable: TableSpec<AccountStatus> = {
  table: 'account_statuses',
  columns: ['id', 'status', 'note', 'updated_at'],
  toRow: (row) => [row.id, row.status, nullable(row.note), row.updatedAt],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      status: row.status as AccountStatus['status'],
      note: (row.note as string | null) ?? undefined,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const notificationTable: TableSpec<Notification> = {
  table: 'notifications',
  columns: [
    'id',
    'user_id',
    'kind',
    'title',
    'body',
    'href',
    'created_at',
    'read_at',
  ],
  toRow: (notification) => [
    notification.id,
    notification.userId,
    notification.kind,
    notification.title,
    nullable(notification.body),
    notification.href,
    notification.createdAt,
    nullable(notification.readAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      userId: row.user_id as string,
      kind: row.kind as Notification['kind'],
      title: row.title as string,
      body: (row.body as string | null) ?? undefined,
      href: row.href as string,
      createdAt: isoString(row.created_at) as string,
      readAt: isoString(row.read_at),
    }),
}

export const reviewTable: TableSpec<Review> = {
  table: 'reviews',
  columns: [
    'id',
    'listing_id',
    'seller_user_id',
    'reviewer_user_id',
    'source_kind',
    'source_id',
    'rating',
    'comment',
    'created_at',
  ],
  toRow: (review) => [
    review.id,
    review.listingId,
    review.sellerUserId,
    review.reviewerUserId,
    review.sourceKind,
    review.sourceId,
    review.rating,
    nullable(review.comment),
    review.createdAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      sellerUserId: row.seller_user_id as string,
      reviewerUserId: row.reviewer_user_id as string,
      sourceKind: row.source_kind as Review['sourceKind'],
      sourceId: row.source_id as string,
      rating: row.rating as number,
      comment: (row.comment as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
    }),
}

export const threadReadTable: TableSpec<ThreadRead> = {
  table: 'thread_reads',
  columns: ['id', 'thread_id', 'user_id', 'read_at'],
  toRow: (read) => [read.id, read.threadId, read.userId, read.readAt],
  fromRow: (row: Row) => ({
    id: row.id as string,
    threadId: row.thread_id as string,
    userId: row.user_id as string,
    readAt: isoString(row.read_at) as string,
  }),
}

export const carrierProfileTable: TableSpec<CarrierProfile> = {
  table: 'carrier_profiles',
  columns: [
    'id',
    'name',
    'kind',
    'prefecture',
    'vehicles',
    'service_areas',
    'note',
    'created_at',
    'updated_at',
  ],
  toRow: (profile) => [
    profile.id,
    profile.name,
    profile.kind,
    profile.prefecture,
    profile.vehicles,
    profile.serviceAreas,
    nullable(profile.note),
    profile.createdAt,
    profile.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      name: row.name as string,
      kind: row.kind as CarrierProfile['kind'],
      prefecture: row.prefecture as string,
      vehicles: row.vehicles as string[],
      serviceAreas: row.service_areas as string[],
      note: (row.note as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const orderTable: TableSpec<Order> = {
  table: 'orders',
  columns: [
    'id',
    'listing_id',
    'buyer_user_id',
    'seller_user_id',
    'price',
    'status',
    'message',
    'source_lease_id',
    'created_at',
    'updated_at',
  ],
  toRow: (order) => [
    order.id,
    order.listingId,
    order.buyerUserId,
    order.sellerUserId,
    order.price,
    order.status,
    nullable(order.message),
    nullable(order.sourceLeaseId),
    order.createdAt,
    order.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      buyerUserId: row.buyer_user_id as string,
      sellerUserId: row.seller_user_id as string,
      price: row.price as number,
      status: row.status as Order['status'],
      message: (row.message as string | null) ?? undefined,
      sourceLeaseId: (row.source_lease_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const dealEventTable: TableSpec<DealEvent> = {
  table: 'deal_events',
  columns: [
    'id',
    'deal_kind',
    'deal_id',
    'actor_user_id',
    'status',
    'note',
    'created_at',
  ],
  toRow: (event) => [
    event.id,
    event.dealKind,
    event.dealId,
    nullable(event.actorUserId),
    event.status,
    nullable(event.note),
    event.createdAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      dealKind: row.deal_kind as DealEvent['dealKind'],
      dealId: row.deal_id as string,
      actorUserId: (row.actor_user_id as string | null) ?? undefined,
      status: row.status as string,
      note: (row.note as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
    }),
}
