import 'server-only'

import type { Listing, TransportJob } from '@/lib/data'
import { generateListings } from './generated-listings'

const curatedListings: Listing[] = [
  {
    id: 'car-001',
    name: 'トヨタ プリウス Z 2019年式',
    category: '乗用車',
    maker: 'トヨタ',
    model: 'プリウス Z',
    year: 2019,
    mileageKm: 48_000,
    inspectionExpiresOn: '2027-03-31',
    condition: '目立った傷なし',
    prefecture: '新潟県',
    city: '長岡市',
    image: '/vehicles/sedan.png',
    summary:
      '禁煙・ワンオーナーのハイブリッド。定期点検記録あり。まずは月額リースで乗り、満了時に残価で買い取る流れにも対応します。',
    deals: ['sale', 'lease'],
    salePrice: 2_180_000,
    leasePerMonth: 42_000,
    residualLease: true,
    residualLeaseCreditRate: 40,
    residualLeaseCreditCap: 600_000,
    seller: {
      name: '出品者デモ',
      kind: '中古車販売店',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['ワンオーナー', '禁煙車', '整備記録あり'],
    ownerUserId: 'demo-seller',
  },
  {
    id: 'suv-002',
    name: 'マツダ CX-5 XD Lパッケージ',
    category: 'SUV',
    maker: 'マツダ',
    model: 'CX-5 XD Lパッケージ',
    year: 2017,
    mileageKm: 86_500,
    inspectionExpiresOn: '2026-11-30',
    condition: '使用感あり',
    prefecture: '秋田県',
    city: '大仙市',
    image: '/vehicles/suv.png',
    summary:
      'ディーゼル4WD。冬道に強く、スタッドレス込みでお渡しできます。長距離通勤向けに月額リースの相談も歓迎です。',
    deals: ['sale', 'lease'],
    salePrice: 1_680_000,
    leasePerMonth: 36_000,
    residualLease: true,
    residualLeaseCreditRate: 40,
    residualLeaseCreditCap: 480_000,
    seller: {
      name: '出品者デモ',
      kind: '中古車販売店',
      rating: 4.6,
      reviews: 58,
    },
    tags: ['4WD', 'ディーゼル', 'スタッドレス付'],
    ownerUserId: 'demo-seller',
  },
  {
    id: 'kei-003',
    name: 'スズキ アルト L 2020年式',
    category: '軽自動車',
    maker: 'スズキ',
    model: 'アルト L',
    year: 2020,
    mileageKm: 21_300,
    inspectionExpiresOn: '2027-06-30',
    condition: '未使用に近い',
    prefecture: '富山県',
    city: '砺波市',
    image: '/vehicles/kei-car.png',
    summary:
      '通勤とご近所の買い物にちょうどいい軽。走行距離も少なめです。乗ってみて良ければ残価で買い取りもできます。',
    deals: ['sale', 'lease'],
    salePrice: 780_000,
    leasePerMonth: 19_000,
    residualLease: true,
    residualLeaseCreditRate: 40,
    residualLeaseCreditCap: 200_000,
    seller: { name: '田村さん', kind: '個人', rating: 4.9, reviews: 21 },
    tags: ['低走行', '車検2年付', '燃費良好'],
    ownerUserId: 'tamura',
  },
  {
    id: 'van-004',
    name: 'ホンダ N-VAN +STYLE FUN',
    category: 'バン',
    maker: 'ホンダ',
    model: 'N-VAN +STYLE FUN',
    year: 2022,
    mileageKm: 12_800,
    inspectionExpiresOn: '2028-02-29',
    condition: '未使用に近い',
    prefecture: '長野県',
    city: '松本市',
    image: '/vehicles/van.png',
    summary:
      '荷室が広く、開業直後の配送やアウトドアにも使える軽バン。繁忙期だけ台数を増やしたい方の短期リースにも向きます。',
    deals: ['sale', 'lease'],
    salePrice: 1_480_000,
    leasePerMonth: 28_000,
    residualLease: false,
    seller: { name: '小林商会', kind: '法人', rating: 4.7, reviews: 12 },
    tags: ['広い荷室', '軽バン', '自動ブレーキ'],
    ownerUserId: 'kobayashi-trading',
  },
  {
    id: 'trk-005',
    name: 'いすゞ エルフ 2tロング 平ボディ',
    category: 'トラック',
    maker: 'いすゞ',
    model: 'エルフ 2tロング',
    year: 2018,
    mileageKm: 158_000,
    inspectionExpiresOn: '2026-10-31',
    condition: '使用感あり',
    prefecture: '福岡県',
    city: '筑後市',
    image: '/vehicles/truck.png',
    summary:
      '整備工場で点検済みの小型平ボディ。導入前に使い勝手を試したい事業者向けに、月額リース中心でお貸しします。',
    deals: ['lease'],
    leasePerMonth: 68_000,
    residualLease: false,
    seller: { name: 'スカイリース', kind: '法人', rating: 4.5, reviews: 27 },
    tags: ['平ボディ', '事業者向け', '点検済み'],
    ownerUserId: 'sky-lease',
  },
  {
    id: 'suv-006',
    name: 'トヨタ ランドクルーザー プラド TX',
    category: 'SUV',
    maker: 'トヨタ',
    model: 'ランドクルーザー プラド TX',
    year: 2016,
    mileageKm: 112_000,
    inspectionExpiresOn: '2027-01-31',
    condition: '使用感あり',
    prefecture: '北海道',
    city: '帯広市',
    image: '/vehicles/suv.png',
    summary:
      '寒冷地仕様のディーゼル。売却希望です。遠方のため陸送手配のご相談も運搬チャネルから進められます。',
    deals: ['sale'],
    salePrice: 2_980_000,
    residualLease: false,
    seller: {
      name: '十勝オート',
      kind: 'ディーラー',
      rating: 4.4,
      reviews: 41,
    },
    tags: ['寒冷地仕様', '7人乗り', '要陸送手配'],
    ownerUserId: 'tokachi-auto',
  },
]

export const listings: Listing[] = [
  ...curatedListings,
  ...generateListings(42, curatedListings.length + 1),
]

export const transportJobs: TransportJob[] = [
  {
    id: 'tj-01',
    vehicleName: 'いすゞ エルフ 2tロング',
    from: '秋田県 大仙市',
    to: '山形県 天童市',
    distanceKm: 120,
    vehicleSize: '大型車',
    vehicleCount: 1,
    desiredDate: '9/28 午前',
    reward: 38_000,
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'tj-02',
    vehicleName: 'トヨタ プリウス Z',
    from: '新潟県 長岡市',
    to: '新潟県 上越市',
    distanceKm: 75,
    vehicleSize: '普通車',
    vehicleCount: 1,
    desiredDate: '10/3 終日',
    reward: 22_000,
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'tj-03',
    vehicleName: 'スズキ アルト L',
    from: '富山県 砺波市',
    to: '石川県 白山市',
    distanceKm: 55,
    vehicleSize: '軽自動車',
    vehicleCount: 1,
    desiredDate: '10/6 午後',
    reward: 15_000,
    status: '調整中',
    ownerUserId: 'tamura',
  },
  {
    id: 'tj-04',
    vehicleName: 'ホンダ N-VAN 2台',
    from: '長野県 松本市',
    to: '長野県 諏訪市',
    distanceKm: 40,
    vehicleSize: '軽自動車',
    vehicleCount: 2,
    desiredDate: '相談',
    reward: 16_000,
    status: '募集中',
    ownerUserId: 'kobayashi-trading',
  },
  {
    id: 'tj-05',
    vehicleName: 'トヨタ ランドクルーザー プラド TX',
    from: '北海道 帯広市',
    to: '北海道 旭川市',
    distanceKm: 180,
    vehicleSize: '普通車',
    vehicleCount: 1,
    desiredDate: '10/12 午前',
    reward: 52_000,
    status: '募集中',
    ownerUserId: 'tokachi-auto',
  },
  {
    id: 'tj-06',
    vehicleName: 'ダイハツ ハイゼット カーゴ',
    from: '福岡県 筑後市',
    to: '佐賀県 武雄市',
    distanceKm: 45,
    vehicleSize: '軽自動車',
    vehicleCount: 1,
    desiredDate: '10/9 午後',
    reward: 8_000,
    status: '募集中',
    ownerUserId: 'sky-lease',
  },
  {
    id: 'tj-07',
    vehicleName: '日産 セレナ ハイウェイスター',
    from: '滋賀県 長浜市',
    to: '兵庫県 丹波篠山市',
    distanceKm: 110,
    vehicleSize: '普通車',
    vehicleCount: 1,
    desiredDate: '10/15 終日',
    reward: 30_000,
    status: '調整中',
    ownerUserId: 'yamada-cars',
  },
  {
    id: 'tj-08',
    vehicleName: '三菱ふそう キャンター 3t',
    from: '宮城県 登米市',
    to: '岩手県 花巻市',
    distanceKm: 95,
    vehicleSize: '大型車',
    vehicleCount: 1,
    desiredDate: '相談',
    reward: 34_000,
    status: '募集中',
    ownerUserId: 'ito-motors',
  },
  {
    id: 'tj-09',
    vehicleName: 'スズキ ワゴンR 2台まとめて',
    from: '静岡県 掛川市',
    to: '愛知県 豊橋市',
    distanceKm: 70,
    vehicleSize: '軽自動車',
    vehicleCount: 2,
    desiredDate: '10/20 午前',
    reward: 19_000,
    status: '募集中',
    ownerUserId: 'nakamura-motors',
  },
  {
    id: 'tj-10',
    vehicleName: 'マツダ CX-5 XD',
    from: '岡山県 真庭市',
    to: '広島県 東広島市',
    distanceKm: 130,
    vehicleSize: '普通車',
    vehicleCount: 1,
    desiredDate: '10/25 終日',
    reward: 36_000,
    status: '募集中',
    ownerUserId: 'takahashi',
  },
]
