import 'server-only'

import { orderStatusLabels, type Listing, type TransportJob } from '@/lib/data'
import { leaseEndDate, leaseStatusLabels } from '@/lib/residual-lease'
import type {
  AccountStatus,
  CarrierProfile,
  DealEvent,
  DealKind,
  Message,
  Notification,
  Order,
  Lease,
  Review,
  Submission,
  ThreadRead,
} from './store/types'

/**
 * What the marketplace looks like after a few months of use: purchases,
 * leases, threads, hauls, and reviews between the demo accounts and the
 * personas. Loaded on top of the sample listings unless `DEMO_ACTIVITY=off`.
 */
export type DemoActivity = {
  listings: Listing[]
  transportJobs: TransportJob[]
  submissions: Submission[]
  messages: Message[]
  leases: Lease[]
  orders: Order[]
  reviews: Review[]
  carrierProfiles: CarrierProfile[]
  notifications: Notification[]
  threadReads: ThreadRead[]
  accountStatuses: AccountStatus[]
  dealEvents: DealEvent[]
}

/** `at('09-13 10:30')` → ISO timestamp in 2026, JST. */
function at(stamp: string): string {
  const [date, time] = stamp.split(' ')
  return new Date(`2026-${date}T${time}:00+09:00`).toISOString()
}

const sedanImage = '/vehicles/sedan.png'

const listings: Listing[] = [
  {
    id: 'car-101',
    name: 'トヨタ カローラ ツーリング 2021年式',
    category: '乗用車',
    maker: 'トヨタ',
    model: 'カローラ ツーリング W×B',
    year: 2021,
    mileageKm: 31_000,
    inspectionExpiresOn: '2027-05-31',
    condition: '目立った傷なし',
    prefecture: '新潟県',
    city: '長岡市',
    image: sedanImage,
    summary:
      '家族で使っていたワゴン。記録簿付きで状態は良好です。まずは月額リースからでもどうぞ。',
    deals: ['sale', 'lease'],
    salePrice: 1_980_000,
    leasePerMonth: 38_000,
    residualLease: true,
    residualLeaseCreditRate: 40,
    residualLeaseCreditCap: 500_000,
    seller: {
      name: '出品者デモ',
      kind: '中古車販売店',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['ハイブリッド', '禁煙車'],
    ownerUserId: 'demo-seller',
    createdAt: at('09-13 09:10'),
    updatedAt: at('09-13 09:10'),
    moderationStatus: 'pending',
  },
  {
    id: 'suv-102',
    name: '三菱 アウトランダー PHEV 2015年式',
    category: 'SUV',
    maker: '三菱',
    model: 'アウトランダー PHEV G',
    year: 2015,
    mileageKm: 124_000,
    inspectionExpiresOn: '2026-12-31',
    condition: '使用感あり',
    prefecture: '山形県',
    city: '鶴岡市',
    image: '/vehicles/suv.png',
    summary: '冬場の主力として使っていました。乗り換えのため手放します。',
    deals: ['sale'],
    salePrice: 1_240_000,
    residualLease: false,
    seller: {
      name: '山田カーズ',
      kind: '中古車販売店',
      rating: 4.7,
      reviews: 63,
    },
    tags: ['4WD', '整備記録あり'],
    ownerUserId: 'yamada-cars',
    createdAt: at('09-12 18:40'),
    updatedAt: at('09-12 18:40'),
    moderationStatus: 'pending',
  },
  {
    id: 'van-103',
    name: 'ダイハツ ハイゼット カーゴ 2020年式',
    category: 'バン',
    maker: 'ダイハツ',
    model: 'ハイゼット カーゴ クルーズ',
    year: 2020,
    mileageKm: 42_000,
    inspectionExpiresOn: '2027-08-31',
    condition: '未使用に近い',
    prefecture: '東京都',
    city: '八王子市',
    image: '/vehicles/van.png',
    summary: '運営が検証用に出品している軽バン。短期のリース向けです。',
    deals: ['lease'],
    leasePerMonth: 24_000,
    residualLease: false,
    seller: { name: '運営デモ', kind: '法人', rating: 0, reviews: 0 },
    tags: ['軽バン', '広い荷室'],
    ownerUserId: 'demo-admin',
    createdAt: at('08-30 11:00'),
    updatedAt: at('08-30 11:20'),
    moderationStatus: 'approved',
    moderatedAt: at('08-30 11:20'),
  },
  {
    id: 'van-104',
    name: 'スズキ エブリイ ワゴン PZ 2021年式',
    category: 'バン',
    maker: 'スズキ',
    model: 'エブリイ ワゴン PZ',
    year: 2021,
    mileageKm: 18_600,
    inspectionExpiresOn: '2027-09-30',
    condition: '未使用に近い',
    prefecture: '新潟県',
    city: '長岡市',
    image: '/vehicles/van.png',
    summary: 'セカンドカーとして購入したもの。走行距離も少なめです。',
    deals: ['sale'],
    salePrice: 1_180_000,
    residualLease: false,
    seller: {
      name: '出品者デモ',
      kind: '中古車販売店',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['低走行', '軽バン'],
    ownerUserId: 'demo-seller',
    createdAt: at('07-20 09:00'),
    updatedAt: at('08-12 16:00'),
    moderationStatus: 'approved',
    moderatedAt: at('07-20 10:00'),
    withdrawnAt: at('08-12 16:00'),
  },
  {
    id: 'kei-105',
    name: 'ダイハツ タント X 2018年式',
    category: '軽自動車',
    maker: 'ダイハツ',
    model: 'タント X',
    year: 2018,
    mileageKm: 62_400,
    inspectionExpiresOn: '2026-11-30',
    condition: '目立った傷なし',
    prefecture: '新潟県',
    city: '南魚沼市',
    image: '/vehicles/kei-car.png',
    summary: '買い替えに伴い売却しました。スライドドアで乗り降りが楽な一台。',
    deals: ['sale'],
    salePrice: 680_000,
    residualLease: false,
    seller: {
      name: '中村モータース',
      kind: '中古車販売店',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['スライドドア', '車検付'],
    ownerUserId: 'nakamura-motors',
    createdAt: at('06-05 08:30'),
    updatedAt: at('07-02 12:00'),
    moderationStatus: 'approved',
    moderatedAt: at('06-05 09:00'),
    withdrawnAt: at('07-02 12:00'),
  },
  {
    id: 'trk-106',
    name: '日野 デュトロ 3t 冷蔵冷凍車 2024年式',
    category: 'トラック',
    maker: '日野',
    model: 'デュトロ 3t 冷蔵冷凍車',
    year: 2024,
    mileageKm: 48_000,
    inspectionExpiresOn: '2027-04-30',
    condition: '未使用に近い',
    prefecture: '新潟県',
    city: '長岡市',
    image: '/vehicles/truck.png',
    summary: '繁忙期の増車用に貸し出しています。冷凍機の稼働も確認済みです。',
    deals: ['lease'],
    leasePerMonth: 98_000,
    residualLease: false,
    seller: {
      name: '出品者デモ',
      kind: '中古車販売店',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['冷凍機付', '事業者向け'],
    ownerUserId: 'demo-seller',
    createdAt: at('08-01 10:00'),
    updatedAt: at('08-01 10:30'),
    moderationStatus: 'approved',
    moderatedAt: at('08-01 10:30'),
  },
]

const transportJobs: TransportJob[] = [
  {
    id: 'tj-101',
    vehicleName: 'トヨタ カローラ ツーリング',
    from: '新潟県 長岡市',
    to: '新潟県 新潟市',
    distanceKm: 60,
    vehicleSize: '普通車',
    vehicleCount: 1,
    desiredDate: '9/13 午前',
    reward: 18_000,
    status: '運搬中',
    ownerUserId: 'demo-seller',
    createdAt: at('09-08 09:00'),
    updatedAt: at('09-13 08:05'),
    moderationStatus: 'approved',
    moderatedAt: at('09-08 09:30'),
  },
  {
    id: 'tj-102',
    vehicleName: '日野 デュトロ 3t 冷蔵冷凍車',
    from: '富山県 砺波市',
    to: '長野県 飯山市',
    distanceKm: 130,
    vehicleSize: '大型車',
    vehicleCount: 1,
    desiredDate: '9/20 終日',
    reward: 32_000,
    status: '調整中',
    ownerUserId: 'ito-motors',
    createdAt: at('09-05 14:00'),
    updatedAt: at('09-11 17:30'),
    moderationStatus: 'approved',
    moderatedAt: at('09-05 14:20'),
  },
  {
    id: 'tj-103',
    vehicleName: 'スズキ エブリイ ワゴン 2台',
    from: '群馬県 前橋市',
    to: '埼玉県 深谷市',
    distanceKm: 45,
    vehicleSize: '軽自動車',
    vehicleCount: 2,
    desiredDate: '相談',
    reward: 14_000,
    status: '募集中',
    ownerUserId: 'kato',
    createdAt: at('09-13 07:45'),
    updatedAt: at('09-13 07:45'),
    moderationStatus: 'pending',
  },
  {
    id: 'tj-104',
    vehicleName: 'ダイハツ タント X',
    from: '新潟県 南魚沼市',
    to: '群馬県 高崎市',
    distanceKm: 140,
    vehicleSize: '軽自動車',
    vehicleCount: 1,
    desiredDate: '7/5 午前',
    reward: 28_000,
    status: '完了',
    ownerUserId: 'nakamura-motors',
    createdAt: at('06-28 10:00'),
    updatedAt: at('07-05 15:40'),
    moderationStatus: 'approved',
    moderatedAt: at('06-28 10:30'),
  },
]

function lease(
  input: Omit<Lease, 'endDate' | 'leaseTotal' | 'createdAt' | 'updatedAt'> & {
    createdAt: string
    updatedAt: string
  },
): Lease {
  return {
    ...input,
    endDate: leaseEndDate(input.startDate, input.months) as string,
    leaseTotal: input.months * input.leasePerMonth,
  }
}

const leases: Lease[] = [
  lease({
    id: 'l-101',
    listingId: 'car-001',
    lesseeUserId: 'demo-user',
    startDate: '2026-10-05',
    months: 24,
    leasePerMonth: 42_000,
    salePrice: 2_180_000,
    creditRate: 40,
    creditCap: 600_000,
    status: 'requested',
    createdAt: at('09-12 20:15'),
    updatedAt: at('09-12 20:15'),
  }),
  lease({
    id: 'l-102',
    listingId: 'trk-005',
    lesseeUserId: 'suzuki',
    startDate: '2026-09-01',
    months: 12,
    leasePerMonth: 68_000,
    status: 'active',
    createdAt: at('08-20 09:30'),
    updatedAt: at('09-01 08:00'),
  }),
  lease({
    id: 'l-103',
    listingId: 'kei-003',
    lesseeUserId: 'demo-user',
    startDate: '2025-08-20',
    months: 12,
    leasePerMonth: 19_000,
    salePrice: 780_000,
    creditRate: 40,
    creditCap: 200_000,
    status: 'completed',
    createdAt: at('08-10 12:00'),
    updatedAt: at('08-25 09:10'),
  }),
  lease({
    id: 'l-104',
    listingId: 'suv-002',
    lesseeUserId: 'demo-admin',
    startDate: '2026-10-01',
    months: 36,
    leasePerMonth: 36_000,
    salePrice: 1_680_000,
    creditRate: 40,
    creditCap: 480_000,
    status: 'requested',
    createdAt: at('09-13 08:50'),
    updatedAt: at('09-13 08:50'),
  }),
  lease({
    id: 'l-105',
    listingId: 'car-001',
    lesseeUserId: 'ito-motors',
    startDate: '2025-07-01',
    months: 12,
    leasePerMonth: 42_000,
    salePrice: 2_180_000,
    creditRate: 40,
    creditCap: 600_000,
    status: 'completed',
    createdAt: at('06-20 15:00'),
    updatedAt: at('07-06 10:00'),
  }),
  lease({
    id: 'l-106',
    listingId: 'van-004',
    lesseeUserId: 'takahashi',
    startDate: '2026-09-01',
    months: 12,
    leasePerMonth: 28_000,
    status: 'cancelled',
    createdAt: at('08-28 19:00'),
    updatedAt: at('08-30 08:20'),
  }),
  lease({
    id: 'l-107',
    listingId: 'trk-106',
    lesseeUserId: 'demo-user',
    startDate: '2026-09-12',
    months: 24,
    leasePerMonth: 98_000,
    status: 'active',
    createdAt: at('09-03 10:00'),
    updatedAt: at('09-12 07:30'),
  }),
  lease({
    id: 'l-108',
    listingId: 'suv-002',
    lesseeUserId: 'suzuki',
    startDate: '2025-06-10',
    months: 12,
    leasePerMonth: 36_000,
    salePrice: 1_680_000,
    creditRate: 40,
    creditCap: 480_000,
    status: 'completed',
    createdAt: at('05-30 13:00'),
    updatedAt: at('06-13 11:00'),
  }),
]

const orders: Order[] = [
  {
    id: 'o-101',
    listingId: 'suv-002',
    buyerUserId: 'suzuki',
    sellerUserId: 'demo-seller',
    price: 24_500_000,
    status: 'requested',
    message: '6月にリースした際の状態が良かったので購入したいです。',
    createdAt: at('09-13 09:40'),
    updatedAt: at('09-13 09:40'),
  },
  {
    id: 'o-102',
    listingId: 'suv-006',
    buyerUserId: 'demo-user',
    sellerUserId: 'tokachi-auto',
    price: 21_000_000,
    status: 'requested',
    message: '輸送は運搬マッチングで手配する予定です。',
    createdAt: at('09-11 21:00'),
    updatedAt: at('09-11 21:00'),
  },
  {
    id: 'o-103',
    listingId: 'van-004',
    buyerUserId: 'ito-motors',
    sellerUserId: 'kobayashi-trading',
    price: 128_000,
    status: 'accepted',
    createdAt: at('09-09 10:00'),
    updatedAt: at('09-10 09:15'),
  },
  {
    id: 'o-104',
    listingId: 'van-104',
    buyerUserId: 'demo-user',
    sellerUserId: 'demo-seller',
    price: 98_000,
    status: 'completed',
    createdAt: at('08-05 12:00'),
    updatedAt: at('08-12 16:00'),
  },
  {
    id: 'o-105',
    listingId: 'kei-105',
    buyerUserId: 'kato',
    sellerUserId: 'nakamura-motors',
    price: 1_450_000,
    status: 'completed',
    createdAt: at('06-20 09:00'),
    updatedAt: at('07-02 12:00'),
  },
  {
    id: 'o-106',
    listingId: 'suv-006',
    buyerUserId: 'demo-admin',
    sellerUserId: 'tokachi-auto',
    price: 21_000_000,
    status: 'cancelled',
    message: '検証用の申込です。',
    createdAt: at('09-02 15:00'),
    updatedAt: at('09-03 09:00'),
  },
]

const submissions: Submission[] = [
  {
    id: 's-101',
    kind: 'listingInquiry',
    targetId: 'car-001',
    userId: 'suzuki',
    receivedAt: at('09-13 10:05'),
    payload: {
      mode: 'lease',
      name: '鈴木さん',
      email: 'suzuki@example.com',
      preferredDate: '2026-10-20',
      message: '10月から24ヶ月で借りたいです。冬タイヤは付属しますか？',
    },
  },
  {
    id: 's-102',
    kind: 'listingInquiry',
    targetId: 'suv-002',
    userId: 'demo-user',
    receivedAt: at('09-11 19:20'),
    payload: {
      mode: 'question',
      name: '利用者デモ',
      email: 'user@example.com',
      message: '車検の残り期間は相談できますか？',
    },
    status: 'in_progress',
  },
  {
    id: 's-103',
    kind: 'listingInquiry',
    targetId: 'van-004',
    userId: 'kato',
    receivedAt: at('09-06 08:00'),
    payload: {
      mode: 'buy',
      name: '加藤さん',
      email: 'kato@example.com',
      message: '購入希望です。引き取りに伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-104',
    kind: 'listingInquiry',
    targetId: 'trk-005',
    userId: 'demo-admin',
    receivedAt: at('09-12 11:30'),
    payload: {
      mode: 'lease',
      name: '運営デモ',
      email: 'admin@example.com',
      preferredDate: '2026-09-25',
      message: '講習用に2日間借りられますか？',
    },
  },
  {
    id: 's-105',
    kind: 'transportApplication',
    targetId: 'tj-101',
    userId: 'okada',
    receivedAt: at('09-08 12:00'),
    payload: {
      name: '岡田さん',
      email: 'okada@example.com',
      vehicle: '2台積みキャリアカー',
      availableDate: '2026-09-13',
      message: '当日午前に伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-106',
    kind: 'transportApplication',
    targetId: 'tj-01',
    userId: 'hokuriku-carrier',
    receivedAt: at('09-13 09:55'),
    payload: {
      name: '北陸陸送',
      email: 'hokuriku-carrier@example.com',
      vehicle: 'セルフローダー',
      availableDate: '2026-09-28',
      message: '大仙から天童は定期便のルートです。',
    },
  },
  {
    id: 's-107',
    kind: 'transportApplication',
    targetId: 'tj-05',
    userId: 'demo-user',
    receivedAt: at('09-12 16:45'),
    payload: {
      name: '利用者デモ',
      email: 'user@example.com',
      vehicle: '2台積みキャリアカー',
      availableDate: '2026-10-12',
    },
  },
  {
    id: 's-108',
    kind: 'transportInquiry',
    targetId: 'tj-02',
    userId: 'yamamoto-transport',
    receivedAt: at('09-10 13:10'),
    payload: { message: '積み込みにフォークリフトは用意されますか？' },
    status: 'in_progress',
  },
  {
    id: 's-109',
    kind: 'transportApplication',
    targetId: 'tj-102',
    userId: 'hokuriku-carrier',
    receivedAt: at('09-06 09:00'),
    payload: {
      name: '北陸陸送',
      email: 'hokuriku-carrier@example.com',
      vehicle: 'セルフローダー',
      availableDate: '2026-09-20',
    },
    status: 'agreed',
  },
  {
    id: 's-110',
    kind: 'transportApplication',
    targetId: 'tj-104',
    userId: 'yamamoto-transport',
    receivedAt: at('06-29 10:00'),
    payload: {
      name: '山本トランスポート',
      email: 'yamamoto-transport@example.com',
      vehicle: '5台積みキャリアカー',
      availableDate: '2026-07-05',
    },
    status: 'agreed',
  },
  {
    id: 's-111',
    kind: 'listingInquiry',
    targetId: 'suv-006',
    userId: 'takahashi',
    receivedAt: at('08-20 20:00'),
    payload: {
      mode: 'buy',
      name: '高橋さん',
      email: 'takahashi@example.com',
      message: '値下げの相談はできますか？',
    },
    status: 'declined',
  },
  {
    id: 's-112',
    kind: 'transportInquiry',
    targetId: 'tj-01',
    userId: 'demo-user',
    receivedAt: at('09-12 09:00'),
    payload: { message: '希望日の前日搬入でも大丈夫ですか？' },
    status: 'in_progress',
  },
]

const messages: Message[] = [
  {
    id: 'm-101',
    threadId: 's-102',
    senderUserId: 'demo-seller',
    body: '車検は満了日まで残っています。陸送も合わせて見積もりします。',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'm-102',
    threadId: 's-112',
    senderUserId: 'demo-seller',
    body: '前日搬入で問題ありません。倉庫の鍵は当日お渡しします。',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'm-103',
    threadId: 's-103',
    senderUserId: 'kobayashi-trading',
    body: 'ありがとうございます。9月中の引き取りでお願いします。',
    createdAt: at('09-06 18:00'),
  },
  {
    id: 'm-104',
    threadId: 's-108',
    senderUserId: 'demo-seller',
    body: 'フォークリフトは出発地に用意があります。',
    createdAt: at('09-10 15:00'),
  },
]

const reviews: Review[] = [
  {
    id: 'rv-101',
    listingId: 'van-104',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'demo-user',
    sourceKind: 'order',
    sourceId: 'o-104',
    rating: 5,
    comment: '説明どおりほぼ新品でした。引き渡しもスムーズ。',
    createdAt: at('08-13 21:00'),
  },
  {
    id: 'rv-102',
    listingId: 'kei-003',
    sellerUserId: 'tamura',
    reviewerUserId: 'demo-user',
    sourceKind: 'lease',
    sourceId: 'l-103',
    rating: 5,
    comment: '整備が行き届いていて、初めての6条でも扱いやすかったです。',
    createdAt: at('08-26 07:40'),
  },
  {
    id: 'rv-103',
    listingId: 'car-001',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'ito-motors',
    sourceKind: 'lease',
    sourceId: 'l-105',
    rating: 4,
    comment: '状態は良好。返却時の清掃基準を事前に聞いておくと安心です。',
    createdAt: at('07-07 09:00'),
  },
  {
    id: 'rv-104',
    listingId: 'kei-105',
    sellerUserId: 'nakamura-motors',
    reviewerUserId: 'kato',
    sourceKind: 'order',
    sourceId: 'o-105',
    rating: 4,
    comment: '価格相応。運搬の手配まで相談に乗ってもらえました。',
    createdAt: at('07-04 19:30'),
  },
  {
    id: 'rv-105',
    listingId: 'suv-002',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'suzuki',
    sourceKind: 'lease',
    sourceId: 'l-108',
    rating: 3,
    comment: '車両は問題なし。受け渡し時間の連絡がやや遅めでした。',
    createdAt: at('06-14 20:10'),
  },
]

const carrierProfiles: CarrierProfile[] = [
  {
    id: 'demo-user',
    name: '利用者デモ',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['2台積みキャリアカー'],
    serviceAreas: ['新潟県', '長野県', '富山県'],
    note: '週末中心に対応できます。',
    createdAt: at('08-15 10:00'),
    updatedAt: at('08-15 10:00'),
  },
  {
    id: 'okada',
    name: '岡田さん',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['積載車（1台）', '2台積みキャリアカー'],
    serviceAreas: ['新潟県'],
    createdAt: at('07-10 09:00'),
    updatedAt: at('07-10 09:00'),
  },
  {
    id: 'hokuriku-carrier',
    name: '北陸陸送',
    kind: '法人',
    prefecture: '石川県',
    vehicles: ['セルフローダー', '5台積みキャリアカー'],
    serviceAreas: ['石川県', '富山県', '福井県', '新潟県', '秋田県', '山形県'],
    note: '北陸〜東北の定期便あり。',
    createdAt: at('05-12 11:00'),
    updatedAt: at('08-01 11:00'),
  },
  {
    id: 'yamamoto-transport',
    name: '山本トランスポート',
    kind: '法人',
    prefecture: '北海道',
    vehicles: ['セルフローダー', '5台積みキャリアカー'],
    serviceAreas: ['北海道', '新潟県', '群馬県'],
    createdAt: at('04-20 09:00'),
    updatedAt: at('04-20 09:00'),
  },
]

const notifications: Notification[] = [
  {
    id: 'n-101',
    userId: 'demo-seller',
    kind: 'inquiry',
    title: '問い合わせが届きました',
    body: 'トヨタ プリウス Z GLシリーズ',
    href: '/account/threads/s-101',
    createdAt: at('09-13 10:05'),
  },
  {
    id: 'n-102',
    userId: 'demo-seller',
    kind: 'application',
    title: '応募が届きました',
    body: 'マツダ CX-5 XD',
    href: '/account/threads/s-106',
    createdAt: at('09-13 09:55'),
  },
  {
    id: 'n-103',
    userId: 'demo-seller',
    kind: 'lease',
    title: '購入の申込が届きました',
    body: 'マツダ CX-5 XD Lパッケージ',
    href: '/account',
    createdAt: at('09-13 09:40'),
  },
  {
    id: 'n-104',
    userId: 'demo-seller',
    kind: 'lease',
    title: 'リースの申込が届きました',
    body: 'マツダ CX-5 XD Lパッケージ',
    href: '/account',
    createdAt: at('09-13 08:50'),
  },
  {
    id: 'n-105',
    userId: 'demo-seller',
    kind: 'application',
    title: '運搬が始まりました',
    body: 'トヨタ カローラ ツーリング',
    href: '/transport/tj-101',
    createdAt: at('09-13 08:05'),
  },
  {
    id: 'n-106',
    userId: 'demo-seller',
    kind: 'lease',
    title: 'リースの申込が届きました',
    body: 'トヨタ プリウス Z GLシリーズ',
    href: '/account',
    createdAt: at('09-12 20:15'),
    readAt: at('09-12 21:00'),
  },
  {
    id: 'n-107',
    userId: 'demo-seller',
    kind: 'application',
    title: '案件への質問が届きました',
    body: '乗用車 Z',
    href: '/account/threads/s-108',
    createdAt: at('09-10 13:10'),
    readAt: at('09-10 14:55'),
  },
  {
    id: 'n-108',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'マツダ CX-5 XD Lパッケージ',
    href: '/account/threads/s-102',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'n-109',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'マツダ CX-5 XD',
    href: '/account/threads/s-112',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'n-110',
    userId: 'demo-user',
    kind: 'lease',
    title: `リースが「${leaseStatusLabels.active}」になりました`,
    body: '日野 デュトロ 3t 冷蔵冷凍車',
    href: '/account',
    createdAt: at('09-12 07:30'),
  },
  {
    id: 'n-111',
    userId: 'demo-user',
    kind: 'lease',
    title: `リースが「${leaseStatusLabels.completed}」になりました`,
    body: 'ダイハツ タント X',
    href: '/account',
    createdAt: at('08-25 09:10'),
    readAt: at('08-25 12:00'),
  },
  {
    id: 'n-112',
    userId: 'demo-user',
    kind: 'lease',
    title: `購入が「${orderStatusLabels.completed}」になりました`,
    body: 'ダイハツ ハイゼット F220 サラダ',
    href: '/account',
    createdAt: at('08-12 16:00'),
    readAt: at('08-12 18:30'),
  },
  {
    id: 'n-113',
    userId: 'demo-admin',
    kind: 'moderation',
    title: '出品が承認されました',
    body: 'トヨタ 管理機 陽菜 TRS70',
    href: '/listings/van-103',
    createdAt: at('08-30 11:20'),
    readAt: at('08-30 11:25'),
  },
  {
    id: 'n-114',
    userId: 'demo-admin',
    kind: 'lease',
    title: `購入が「${orderStatusLabels.cancelled}」になりました`,
    body: 'トヨタ ランドクルーザー プラド TX',
    href: '/account',
    createdAt: at('09-03 09:00'),
  },
]

const threadReads: ThreadRead[] = [
  { threadId: 's-102', userId: 'demo-seller', readAt: at('09-12 08:30') },
  { threadId: 's-112', userId: 'demo-seller', readAt: at('09-12 12:10') },
  { threadId: 's-108', userId: 'demo-seller', readAt: at('09-10 15:00') },
  { threadId: 's-105', userId: 'demo-seller', readAt: at('09-09 18:00') },
  { threadId: 's-103', userId: 'kobayashi-trading', readAt: at('09-06 18:00') },
].map((read) => ({ id: `${read.threadId}:${read.userId}`, ...read }))

const accountStatuses: AccountStatus[] = [
  {
    id: 'watanabe',
    status: 'suspended',
    note: '本人確認の書類が未提出',
    updatedAt: at('09-04 10:00'),
  },
]

type EventSeed = [DealKind, string, string, string | undefined, string, string?]

/** [kind, dealId, status, actor, when, note] — order does not matter. */
const eventSeeds: EventSeed[] = [
  [
    'order',
    'o-101',
    'requested',
    'suzuki',
    '09-13 09:40',
    '6月にリースした際の状態が良かったので購入したいです。',
  ],
  [
    'order',
    'o-102',
    'requested',
    'demo-user',
    '09-11 21:00',
    '輸送は運搬マッチングで手配する予定です。',
  ],
  ['order', 'o-103', 'requested', 'ito-motors', '09-09 10:00'],
  ['order', 'o-103', 'accepted', 'kobayashi-trading', '09-10 09:15'],
  ['order', 'o-104', 'requested', 'demo-user', '08-05 12:00'],
  ['order', 'o-104', 'accepted', 'demo-seller', '08-06 08:00'],
  ['order', 'o-104', 'delivered', 'demo-seller', '08-10 14:00'],
  ['order', 'o-104', 'completed', 'demo-user', '08-12 16:00'],
  ['order', 'o-105', 'requested', 'kato', '06-20 09:00'],
  ['order', 'o-105', 'accepted', 'nakamura-motors', '06-21 07:30'],
  ['order', 'o-105', 'delivered', 'nakamura-motors', '06-30 11:00'],
  ['order', 'o-105', 'completed', 'kato', '07-02 12:00'],
  [
    'order',
    'o-106',
    'requested',
    'demo-admin',
    '09-02 15:00',
    '検証用の申込です。',
  ],
  ['order', 'o-106', 'cancelled', 'demo-admin', '09-03 09:00'],
  [
    'lease',
    'l-101',
    'requested',
    'demo-user',
    '09-12 20:15',
    '2026-10-05 〜 2026-10-08',
  ],
  [
    'lease',
    'l-102',
    'requested',
    'suzuki',
    '09-01 09:30',
    '2026-09-10 〜 2026-09-16',
  ],
  ['lease', 'l-102', 'active', 'sky-lease', '09-10 08:00'],
  [
    'lease',
    'l-103',
    'requested',
    'demo-user',
    '08-10 12:00',
    '2026-08-20 〜 2026-08-24',
  ],
  ['lease', 'l-103', 'active', 'tamura', '08-20 09:00'],
  ['lease', 'l-103', 'completed', 'tamura', '08-25 09:10'],
  [
    'lease',
    'l-104',
    'requested',
    'demo-admin',
    '09-13 08:50',
    '2026-10-01 〜 2026-10-03',
  ],
  [
    'lease',
    'l-105',
    'requested',
    'ito-motors',
    '06-20 15:00',
    '2026-07-01 〜 2026-07-05',
  ],
  ['lease', 'l-105', 'active', 'demo-seller', '07-01 08:30'],
  ['lease', 'l-105', 'completed', 'demo-seller', '07-06 10:00'],
  [
    'lease',
    'l-106',
    'requested',
    'takahashi',
    '08-28 19:00',
    '2026-09-01 〜 2026-09-02',
  ],
  ['lease', 'l-106', 'cancelled', 'takahashi', '08-30 08:20'],
  [
    'lease',
    'l-107',
    'requested',
    'demo-user',
    '09-03 10:00',
    '2026-09-12 〜 2026-09-18',
  ],
  ['lease', 'l-107', 'active', 'demo-seller', '09-12 07:30'],
  [
    'lease',
    'l-108',
    'requested',
    'suzuki',
    '05-30 13:00',
    '2026-06-10 〜 2026-06-12',
  ],
  ['lease', 'l-108', 'active', 'demo-seller', '06-10 09:00'],
  ['lease', 'l-108', 'completed', 'demo-seller', '06-13 11:00'],
  ['transportJob', 'tj-101', '募集中', 'demo-seller', '09-08 09:00'],
  ['transportJob', 'tj-101', 'approved', undefined, '09-08 09:30'],
  ['transportJob', 'tj-101', '調整中', 'demo-seller', '09-09 18:00'],
  ['transportJob', 'tj-101', '運搬中', 'okada', '09-13 08:05'],
  ['transportJob', 'tj-102', '募集中', 'ito-motors', '09-05 14:00'],
  ['transportJob', 'tj-102', 'approved', undefined, '09-05 14:20'],
  ['transportJob', 'tj-102', '調整中', 'ito-motors', '09-11 17:30'],
  ['transportJob', 'tj-103', '募集中', 'kato', '09-13 07:45'],
  ['transportJob', 'tj-104', '募集中', 'nakamura-motors', '06-28 10:00'],
  ['transportJob', 'tj-104', 'approved', undefined, '06-28 10:30'],
  ['transportJob', 'tj-104', '調整中', 'nakamura-motors', '06-30 09:00'],
  ['transportJob', 'tj-104', '運搬中', 'yamamoto-transport', '07-05 08:00'],
  ['transportJob', 'tj-104', '完了', 'nakamura-motors', '07-05 15:40'],
]

const dealEvents: DealEvent[] = eventSeeds
  .map(([dealKind, dealId, status, actorUserId, when, note], index) => ({
    id: `ev-${String(index + 101)}`,
    dealKind,
    dealId,
    status,
    actorUserId,
    note,
    createdAt: at(when),
  }))
  .sort((a, b) => b.createdAt.localeCompare(a.createdAt))

export const demoActivity: DemoActivity = {
  listings,
  transportJobs,
  submissions,
  messages,
  leases,
  orders,
  reviews,
  carrierProfiles,
  notifications,
  threadReads,
  accountStatuses,
  dealEvents,
}
